// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use process.env directly so `prisma generate`/postinstall
    // doesn't throw when DATABASE_URL isn't provided during install.
    url: process.env.DATABASE_URL,
  },
});
